-- =============================================================================
-- DEPRECATED: This file has been superseded by the migration seed at
-- supabase/migrations/20260228220000_portland_seed.sql
--
-- All Portland bar, whiskey, and bar_whiskey seed data now lives in the
-- authoritative migration file. Do not add data here.
-- =============================================================================
